baseurl = "http://umich.edu/~fencing"
languageCode = "en-us"
title = "University of Michigan Fencing Club"
theme = "club-theme"
copyright = "(c) 2016 University of Michigan Fencing Club"

[params]
  noCategoryLink = true
  description = "Back-to-back USACFC champions!"
  image = "img/2016cfcawards.jpg"
  themeColor = "#003e78"

  # Google Calendar ID used to embed agenda in sidebar and calendar on Schedule page
  # If changing this, make sure to update `content/add_calendar.md`.
  calendarId = "umich.edu_toeb19ptci3123vprh6464i308@group.calendar.google.com"

  practiceLocation = "the <a href='https://www.google.com/maps/place/University+of+Michigan-Sports+Coliseum/@42.2744305,-83.7456399,16z/data=!4m5!3m4!1s0x883cae3762fe5cc1:0xd3f27cff08a1643f!8m2!3d42.2720542!4d-83.7459577?hl=en' target='_blank'> IM Sports Coliseum</a>"
  
  # No default values
  [params.practiceTimes]
    monday = "6-9 pm"
    wednesday = "6-9 pm"
    friday = "7-9 pm"

  [params.social]
    facebook = "umichfencing"
    twitter = "um_fencing"
    instagram = "umfencing"
    youtube = "UCLjqnWZsMBiHfeuEXiUSgGQ"
    community = "https://maizepages.umich.edu/organization/fencing"

  [params.sponsor]
	logo = "img/rec-sports-logo.jpg"
	text = "Michigan Rec Sports Logo"
	link = "https://recsports.umich.edu/"
	size = "100px" # Default: 100px

[[params.mainMenu]]
  name = "Roster"
  link = "roster"

[[params.mainMenu]]
  name = "Schedule"
  link = "schedule"

[[params.mainMenu]]
  name = "Results"
  link = "results"

[[params.mainMenu]]
  name = "Join"
  link = "join"

[[params.mainMenu]]
  name = "About Fencing"
  link = "about_fencing"

[[params.mainMenu]]
  name = "Contact"
  link = "contact"

[[params.mainMenu]]
  name = "Donate"
  link = "donate"
